// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import "./verifier.sol";

enum State { 
    Open, 
    Runoff, 
    Concluded, 
    Cancelled 
}

contract VerifiedVoting is Verifier {

    struct Candidate {
        uint8 id; // id is used to access the candidate using the map
        string name;
        uint256 voteCountRound1;
        uint256 voteCountRound2;
        bool inRunoff; // if two or more candidates have the same number of votes in the first round, inRunoff := true
    }

    address public admin; // The admin can cancel the Voting
    State public electionState;

    uint256 public endTime;
    uint256 public runoffDuration;

    // Using a map to keep track of the candidates it's cheaper than using an array
    mapping(uint256 => Candidate) public candidates;
    uint256 public candidatesCount;

    mapping(address => bool) public isVerifiedAdult;
    mapping(address => uint8) public lastVotedRound; // 0 = never voted, 1 = round 1, 2 = ballot

    uint256[] public tiedCandidates;
    uint256 public winnerId;

   event AccessGranted(address indexed user);

    // Custom errors
    error Unauthorized(address caller);
    error UnderAge(address  caller);
    error NoCandidatesAvailable();
    error VotingIsOver(State currentState);
    error InvalidCandidateIndex(uint256 providedIndex);
    error AlreadyVoted(address voter, State currentState);
    error AlreadyVerified(address voter);
    error OngoingVoting(State currentState);
    error NotInRunoff(Candidate candidate);
    
    //Errors related to proof
    error InvalidProof(Proof proof);
    error StolenProof(Proof proof, address stealer);
    error ProofExpired(uint256 presentTime, uint256 creationTime); 
    error TimestampInTheFuture(uint256 presentTime, uint256 timestamp);

    modifier onlyAdmin() { 
        require(msg.sender == admin, Unauthorized(msg.sender));
        _; 
    }
    modifier onlyVerified() { 
        require(isVerifiedAdult[msg.sender], UnderAge(msg.sender));
         _; 
    }

        modifier requireCandidate() {
        require(candidatesCount > 0, NoCandidatesAvailable());
        _;
    }

    constructor(
        uint256 _durationMinutes, 
        uint256 _runoffDurationMinutes, 
        string[] memory _candidateNames
    ) {
        admin = msg.sender; //The admin is set as the creator of the contract
        electionState = State.Open;
        endTime = block.timestamp + (_durationMinutes * 1 minutes);
        runoffDuration = _runoffDurationMinutes * 1 minutes;

        for(uint8 i = 0; i < _candidateNames.length; i++) {
            candidates[i] = Candidate({
                id: i,
                name: _candidateNames[i],
                voteCountRound1: 0,
                voteCountRound2: 0,
                inRunoff: false
            });
        }
        candidatesCount = _candidateNames.length;
    }

    /// Verifies if the proof is valid based on the IETF ECDSA credentials model
    /// @param proof the proof generated by the circuit
    /// @param current_timestamp the exact timestamp used by the user to generate the proof
    /// @param expiration_timestamp the expiration date of the user's credential
    /// @param expected_attestation_hash the public signature/hash of the recognized Attestation Provider
    function verifyAndRegister (
        Proof memory proof,
        uint256 current_timestamp,
        uint256 expiration_timestamp,
        uint256 expected_attestation_hash
    ) external {

        require(current_timestamp <= block.timestamp, TimestampInTheFuture(block.timestamp, current_timestamp));
        // For safety: after 30 minutes the proof expires and the user needs to compute a new one
        require(block.timestamp - current_timestamp < 30 minutes, ProofExpired(block.timestamp, current_timestamp));

        // Building the public input of the circuit
        uint[5] memory input = [
            current_timestamp, 
            expiration_timestamp,
            expected_attestation_hash,
            uint256(uint160(msg.sender)),   //The address of the sender is used to bind the proof to its owner and prevent it from being used by a different address
            uint(1)                                                   // expected output of the circuit
        ];

        require(!isVerifiedAdult[msg.sender], AlreadyVerified(msg.sender)); 
        require(verifyTx(proof, input), InvalidProof(proof));
        require(input[3] == uint256(uint160(msg.sender)), StolenProof(proof, msg.sender));

        isVerifiedAdult[msg.sender] = true;
        emit AccessGranted(msg.sender);
    }

    function vote(uint256 _candidateId) external onlyVerified requireCandidate {
        require(_candidateId < candidatesCount, InvalidCandidateIndex(_candidateId));

        if (electionState == State.Open) {
            require(block.timestamp <= endTime, VotingIsOver(electionState));
            require(lastVotedRound[msg.sender] < 1, AlreadyVoted(msg.sender, electionState));
            
            lastVotedRound[msg.sender] = 1;
            candidates[_candidateId].voteCountRound1++;

        } else if (electionState == State.Runoff) {
            require(block.timestamp <= endTime, VotingIsOver(electionState));
            require(candidates[_candidateId].inRunoff,  NotInRunoff(candidates[_candidateId]));
            require(lastVotedRound[msg.sender] < 2, AlreadyVoted(msg.sender, electionState));

            lastVotedRound[msg.sender] = 2;
            candidates[_candidateId].voteCountRound2++;
        } else {
            revert VotingIsOver(electionState);
        }
    }

    function _tallyRound1() internal {
        uint256 maxVotes = 0;
        delete tiedCandidates;

        for (uint256 i = 0; i < candidatesCount; i++) {
            uint256 v = candidates[i].voteCountRound1;
            if (v > maxVotes) {
                maxVotes = v;
                delete tiedCandidates;
                tiedCandidates.push(i);
            } else if (v == maxVotes && v > 0) {
                tiedCandidates.push(i); // Push tied candidate
            }
        }

        // If at least 2 or more candidates are tied, change state into Runoff
        if (tiedCandidates.length > 1) {
            electionState = State.Runoff;
            endTime = block.timestamp + runoffDuration;
            for (uint256 i = 0; i < tiedCandidates.length; i++) {
                candidates[tiedCandidates[i]].inRunoff = true;
            }
        } else if (tiedCandidates.length == 1) {
            electionState = State.Concluded;
            winnerId = tiedCandidates[0];
        } else {
            electionState = State.Concluded; // If no one recieved votes just conclude the election
        }
    }

    /// @notice if the draw persists after the ballot, the contract concludes the voting
    function _tallyRunoff() internal {
        uint256 maxVotes = 0;
        bool stillTied = false;
        uint256 currentWinner = 0;

        for (uint256 i = 0; i < tiedCandidates.length; i++) {
            uint256 cid = tiedCandidates[i];
            uint256 v = candidates[cid].voteCountRound2;

            if (v > maxVotes) {
                maxVotes = v;
                currentWinner = cid;
                stillTied = false;
            } else if (v == maxVotes && v > 0) {
                stillTied = true;
            }
        }

        electionState = State.Concluded;
        if (!stillTied) {
            winnerId = currentWinner;
        }
    }

    /// Called to end the election. If called before endTime revert, if it's the first round call _tallyRound1, else call tallyRunoff that calculates the winner and ends the tally
    function tallyVotes() external {
        require(electionState == State.Open || electionState == State.Runoff, OngoingVoting(electionState));
        require(block.timestamp > endTime, OngoingVoting(electionState));

        if (electionState == State.Open) {
            _tallyRound1();
        } else if (electionState == State.Runoff) {
            _tallyRunoff();
        }
    }

        function cancelVoting() external onlyAdmin {
        electionState = State.Cancelled;
    }
}
